apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bnir7w1ed-nodejs 
  janus-idp.io/tekton: bnir7w1ed-nodejs
  backstage.io/kubernetes-id: bnir7w1ed-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bnir7w1ed-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml