apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bnir7w1ed-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bnir7w1ed-nodejs 
  name: bnir7w1ed-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bnir7w1ed-nodejs 
